#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-bienvenido-gnome
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
        printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
        printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
        printf "\033[1;32m${1}\033[0m\n"
}

case ${1} in
	install|upgrade|'')
		# Para cada usuario en /home/ ...
		for USERNAME in $( ls -1 "/home/" ); do
			# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			if [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:::" /etc/shadow ) -eq 1 ] \
			&& [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) -eq 1 ] \
			&& [ -d "/home/${USERNAME}/.config" ]; then
				ADVERTENCIA 'Removiendo Canaima Bienvenido para el usuario "'${USUARIO}'"'
				# Removemos el lanzador del escritorio de cada usuario
				rm -rf "/home/${USERNAME}/Escritorio/canaima-bienvenido.desktop"

				# Removemos el lanzador automático de canaima-bienvenido-gnome a cada usuario
				rm -rf "/home/${USERNAME}/.config/autostart/canaima-bienvenido-automatico.desktop"

				# Removemos los archivos de configuración de canaima-bienvenido-gnome
				rm -rf "/home/${USERNAME}/.config/canaima-bienvenido/"
			fi
		done
	;;

	abort-upgrade)
	;;

	*)

		ERROR "preinst no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
