.TH SL-H 6 "Dec 2, 2007"
\"
\" Translated into japanese by Hiroyuki Yamamoto <yama1066@gmail.com>
.UC 5
.SH 名称
sl-h \- SLがスクリーンを走るのが好きな人たちを、より楽ませるアニメーションを表示します。
.SH 形式
.B sl-h
[
.B \-alFe
]
.SH 解説
.B sl-h 
SLがスクリーンを走るのが好きな人たちを、より楽ませるアニメーションを表示します。
.B sl
コマンドから少し変更しており、大変長く表示されます。
.PP
次のようなオプションがあります。
.TP
.B \-a
なにかアクシデントがあったようですね。助けを求める人々が悲痛です。
.TP
.B \-l
小さくなります。
.TP
.B \-F
飛びます。("銀河鉄道999"という日本のアニメーションを知ってますか？)
.TP
.B \-e
Ctrl+C で途中で止めることを許します。(とても重くて猛烈である時に、デフォルトとしてください)
.PP
.SH 関連事項
.BR ls (1)
.SH バグ
カレントディレクトリの内容はけっして表示されません。
.SH 著者
.BR sl (6)
は豊田 正史<toyoda@isea.is.titech.ac.jp>により書かれました。
.B sl-h
のコードは泉　智紀<izumi@izumix.org.uk>により書かれ、http://www.izumix.org.uk/sl/ より提供されたパッチを使っています。
このマニュアルはBrian Ristuccia <brianr@debian.org>および武藤　健志<kmuto@debian.org>により、Debian GNU/Linuxシステムのために書かれたもので、
.BR sl (6)
のライセンスに従います。
