#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-bienvenido-gnome
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

case ${1} in
	configure|'')
		# Para cada usuario en /home/ ...
		for USERNAME in $( ls -1 "/home/" ); do
			# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			if [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:::" /etc/shadow ) -eq 1 ] \
			&& [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) -eq 1 ] \
			&& [ -d "/home/${USERNAME}/.config" ] && [ -d "/home/${USERNAME}/Escritorio" ]; then

				ADVERTENCIA 'Instalando Canaima Bienvenido para el usuario "'${USERNAME}'"'

				# Asegurando que el directorio .config/autostart y .config/canaima-bienvenido-gnome/ estén creados
				mkdir -p "/home/${USERNAME}/.config/autostart/"
				mkdir -p "/home/${USERNAME}/.config/canaima-bienvenido-gnome/"
				# con permisos apropiados
				chown -R ${USERNAME}:${USERNAME} "/home/${USERNAME}/.config/autostart/"
				chown -R ${USERNAME}:${USERNAME} "/home/${USERNAME}/.config/canaima-bienvenido-gnome/"


				# Copia del archivo de configuración que determina si debe ejecutarse canaima-bienvenido-gnome al inicio o no
				cp "/etc/skel/.config/canaima-bienvenido-gnome/gui.conf" "/home/${USERNAME}/.config/canaima-bienvenido-gnome/"
				# con permisos apropiados
				chown ${USERNAME}:${USERNAME} "/home/${USERNAME}/.config/canaima-bienvenido-gnome/gui.conf"

				# Copia del lanzador automático de canaima-bienvenido-gnome a cada usuario
				cp "/etc/skel/.config/autostart/canaima-bienvenido-gnome-auto.desktop" "/home/${USERNAME}/.config/autostart/"
				# con permisos apropiados
				chown ${USERNAME}:${USERNAME} "/home/${USERNAME}/.config/autostart/canaima-bienvenido-gnome-auto.desktop"
			fi
		done
	;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)

		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

exit 0
