.\"
.\"  Copyright 1993 Toyoda Masashi.
.\"		(toyoda@is.titech.ac.jp)
.\"	@(#)LS.6	2.02  19/01/93
.\"
.TH LS 6 "Dec 02, 2007"
.UC 5
.SH 名称
LS \- キータイプを矯正します。
.SH 形式
.B LS
[
.B \-alFe
]
.SH 解説
.B LS
は、高度に発展した、キータイプ矯正を目的とするアニメーションプログラムです。
.PP
次のようなオプションがあります。
.TP
.B \-a
なにかアクシデントがあったようですね。助けを求める人々が悲痛です。
.TP
.B \-l
小さくなります。
.TP
.B \-F
飛びます。
.TP
.B \-e
Ctrl+C で途中で止めることを許します。
.PP
.SH 関連事項
.BR sl (6), ls (1)
.SH バグ
カレントディレクトリの内容が表示されることがあります。
.SH 著者
豊田 正史<toyoda@isea.is.titech.ac.jp>
